Analysis of UFC dataset from Kaggle. The data was collected up to UFC 300. 

Link to the datasets: https://www.kaggle.com/datasets/mdabbert/ultimate-ufc-dataset

There are two datasets: 
1. UFC events with detailed data of each fight
2. Data for each fighter throughout their career

In [2]:
import pandas as pd

In [3]:
fighter_stats = pd.read_csv("fighter_stats.csv")

In [4]:
fighter_stats

,name,wins,losses,height,weight,reach,stance,age,SLpM,sig_str_acc,SApM,str_def,td_avg,td_acc,td_def,sub_avg
0,Amanda Ribas,12.0,5.0,160.02,56.70,167.64,Orthodox,30.0,4.63,0.40,3.40,0.61,2.07,0.51,0.85,0.7
1,Rose Namajunas,13.0,6.0,165.10,56.70,165.10,Orthodox,31.0,3.69,0.41,3.51,0.63,1.38,0.47,0.59,0.5
2,Karl Williams,10.0,1.0,190.50,106.59,200.66,Orthodox,34.0,2.87,0.52,1.70,0.60,4.75,0.50,1.00,0.2
3,Justin Tafa,7.0,4.0,182.88,119.75,187.96,Southpaw,30.0,4.09,0.54,5.02,0.47,0.00,0.00,0.50,0.0
4,Edmen Shahbazyan,13.0,4.0,187.96,83.91,190.50,Orthodox,26.0,3.60,0.52,4.09,0.45,2.24,0.38,0.63,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,Thaddeus Luster,0.0,1.0,190.50,95.25,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2475,David Levicki,1.0,3.0,195.58,124.74,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2476,Ray Wizard,0.0,1.0,187.96,102.06,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2477,Sean Daugherty,0.0,2.0,182.88,79.38,NaN,NaN,48.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
fighter_wins = pd.read_csv("fighter_stats.csv", usecols=["name", "wins"], index_col="name").squeeze("columns")

In [9]:
fighter_wins.sort_values(ascending=False)

name
Travis Fulton       253.0
Dan Severn          101.0
Jeremy Horn          91.0
Travis Wiuff         75.0
Yuki Kondo           60.0
                    ...
Robert Lucarelli      0.0
Thaddeus Luster       0.0
Ray Wizard            0.0
Sean Daugherty        0.0
NaN                   NaN
Name: wins, Length: 2479, dtype: float64

In [10]:
fighter_losses = pd.read_csv("fighter_stats.csv", usecols=["name", "losses"], index_col="name").squeeze("columns")

In [14]:
fighter_losses.sort_values().head(50)

name
Payton Talbott           0.0
Frank Hamaker            0.0
Robelis Despaigne        0.0
Tatiana Suarez           0.0
Daniel Marcos            0.0
Lerone Murphy            0.0
Bo Nickal                0.0
Umar Nurmagomedov        0.0
Danny Barlow             0.0
Hyder Amil               0.0
Aliaskhab Khizriev       0.0
Khamzat Chimaev          0.0
Shara Magomedov          0.0
Alex Hunter              0.0
Josefine Knutsson        0.0
Michael Graves           0.0
Tom Murphy               0.0
Movsar Evloev            0.0
Azamat Murzakanov        0.0
Melissa Dixon            0.0
Farid Basharat           0.0
Chris Holdsworth         0.0
Jordan Johnson           0.0
Khabib Nurmagomedov      0.0
Viktoriia Dudakova       0.0
Phillip Miller           0.0
Sione Latu               0.0
Marcelo Mello            0.0
Dmitry Sosnovskiy        0.0
Rafael Estevam           0.0
Shavkat Rakhmonov        0.0
Ryan McGillivray         0.0
HyunSung Park            0.0
Tatsuro Taira            0.0
Talita Alencar           0.0
Bob Cook                 0.0
Clayton Carpenter        0.0
Nurullo Aliev            0.0
Vitor Petrino            0.0
Michael Morales          0.0
Eduarda Moura            0.0
Ian Machado Garry        0.0
Rinya Nakamura           0.0
Mick Parkin              0.0
Ilia Topuria             0.0
Andre Lima               0.0
Muhammad Mokaev          0.0
Jacqueline Cavalcanti    1.0
Ricardo Abreu            1.0
Shauna Bannon            1.0
Name: losses, dtype: float64